/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [4.76KB] > C:\Users\BARAKAT\Downloads\megumins_hat\scene-transformed.glb [444.09KB] (-9230%)
Author: Superior (https://sketchfab.com/SuperiorOne)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/megumins-hat-aac68a65adac4c69a8b0ed15ffd5ef3e
Title: Megumin's Hat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/hat.glb')
  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y +=0.007
  })

  return (
    <group {...props} dispose={null}
    ref={modelRef}
    scale={[1.8,1.8,1.8]}
    rotation={[0.4,-1,0]}
    position={[0,0,0]}
    >
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials['01___Default']} />
    </group>
  )
}

useGLTF.preload('/models/hat.glb')
