/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [18.45KB] > C:\Users\BARAKAT\Downloads\stylized_wood_staff\scene-transformed.glb [146.32KB] (-693%)
Author: Manuela Reis (https://sketchfab.com/Manuela.Reis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-wood-staff-be964c8b493041cab15b449c9f966c25
Title: Stylized Wood Staff
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/staff.glb')
  const  modelRef = useRef();

  useFrame(()=>{
    modelRef.current.rotation.y += 0.04
  })

  
  return (
    <group {...props} dispose={null}
    ref={modelRef}
    scale={[0.45,0.45,0.45]}
    position={[0,-0.2,0]}>
      <mesh geometry={nodes.staff_low_Staff_MAT_0.geometry} material={materials.Staff_MAT} />
    </group>
  )
}

useGLTF.preload('/models/staff.glb')
